spring:
  profiles: node1
  application:
    name: mi-servidor-eureka
    
server:
  port: 8761

 
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : ${EUREKA_URI:http://localhost:8761/eureka},${EUREKA_URI:http://localhost:8762/eureka}
  instance:
    virtual-host-name: myOtherHostName
    metadata-map:
      appOwner : CesarCaceres


logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF

---

spring:
  profiles: node2
  application:
    name: mi-servidor-eureka
  
server:
  port: 8762
     
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : ${EUREKA_URI:http://localhost:8761/eureka},${EUREKA_URI:http://localhost:8762/eureka}
  instance:
    hostname: elotro.com

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF